export const REQUEST_WALLMART_DATA = "REQUEST_WALLMART_DATA";
export const REQUEST_WALLMART_DATA_SUCCESS = "REQUEST_WALLMART_DATA_SUCCESS";
export const REQUEST_WALLMART_DATA_ERROR = "REQUEST_WALLMART_DATA_ERROR";
